### ISSUE TITLE
Does the shaders work normally on IOs using the Metal API?

### ISSUE THREAD

**Issue by reiko-dev** [felixblaschke/shader#3]
I just have one question/curiosity if I'm not mistaken, opengl is deprecated in IOs, and I believe Apple will kill at some point and just use their new Metal API. The question is, will the glsl code work on IOS? We will be able to run these shaders without depending on the OS?
Sorry for the newbie question, I'm starting with shaders :/

**Comment by felixblaschke** [comment]
GLSL is a programming language and not an API. The purpose of the package is to compile this language into SPR-V which is a portable interchange format. On the target platform it will be once again compiled into the main graphics API.

https://en.m.wikipedia.org/wiki/Standard_Portable_Intermediate_Representation

**Comment by reiko-dev** [comment]
Got it, thanks!
