### ISSUE TITLE
WASM compiler 

### ISSUE THREAD

**Issue by jezell** [felixblaschke/shader#5]
This project is great. If shaderc was compiled to WASM it could eliminate the server dependency entirely and still run cross platform:

https://pub.dev/packages/wasm
https://pub.dev/packages/wasm_interop

Looks like this project is doing something like that for web:

https://github.com/BabylonJS/Website/tree/master/build/Demos/WebGPU/lib

**Comment by felixblaschke** [comment]
I don't see any need to further improve on this cause there is a well working official way: https://docs.flutter.dev/development/ui/advanced/shaders

**Comment by jezell** [comment]
@felixblaschke if the official way supported dynamically compiling shaders at runtime, then that would be sufficient, but doesn't it still require them to be compiled at compile time?

In any case, I was suggesting bundling and using a WASM copy of shaderc as an improvement / replacement for this part of the solution:

```If you don't want to rely on the hosted cloud service or the cloud service not available, you can use local compiler.```

As it would eliminate the need for installing the cli or hosting the cloud service. I was imagining a use-case for this that would allow me to dynamically compile shaders into my web app at runtime (been running the web builds of flutter with shader support), certainly cloud hosting the compiler is one way to go about it.

Have opened this issue on the flutter side for some of the missing flutter specific parts to make this possible:

https://github.com/flutter/flutter/issues/124759
